AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: "Simple object detect web app"
  
Globals:
  Function:
    Runtime: nodejs12.x
    Timeout: 60
    MemorySize: 1024
    Tags:
      Application: aws-object-detect-app

Parameters: 
  PictureBucketName:
    Type: String
    Default: object-detect-app-picture-bucket
    Description: "存储用户图片的存储桶名称"
  
  RecordQueueName:
    Type: String
    Default: object-detect-app-record-queue
    Description: "识别记录SQS队列名称"
  
  RecordTableName:
    Type: String
    Default: object-detect-app-record-table
    Description: "识别记录DynamoDB表名称"
  
  ObjectDetectUserPoolName:
    Type: String
    Default: object-detect-app-users
    Description: "Cognito User Pool名称，不能以aws或cognito开头"
    
  ObjectDetectUserPoolClientDomain:
    Type: String
    Default: object-detect-app
    Description: "Cognito登录注册页域名，不能以aws或cognito开头"
  
  WebsiteBucketName:
    Type: String
    Default: object-detect-app-website-bucket
    Description: "托管前端页面的S3存储桶名称"

Resources:
  # API Gateway
  ObjectDetectApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      CorsConfiguration:
        AllowMethods:
          - "*"
        AllowHeaders:
          - "*"
        AllowOrigins:
          - "*"
      Auth:
        Authorizers:
          OpenIdAuthorizer:
            IdentitySource: $request.header.Authorization
            JwtConfiguration:
              audience:
                - !Ref ObjectDetectUserPoolClient
              issuer: !Sub "https://cognito-idp.${AWS::Region}.amazonaws.com/${ObjectDetectUserPool}"
        DefaultAuthorizer: OpenIdAuthorizer
  
  # API Function
  UploadPictureFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/uploadPicture
      Handler: app.handler
      Policies:
        - S3WritePolicy:
            BucketName: !Ref PictureBucket
      Environment:
        Variables:
          BUCKET_NAME: !Ref PictureBucket
      Events:
        UploadPictureApi:
          Type: HttpApi
          Properties:
            Path: /upload
            Method: get
            ApiId: !Ref ObjectDetectApi
            Auth:
              Authorizer: OpenIdAuthorizer
    
  DetectPictureFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/detectPicture
      Handler: app.handler
      Environment:
        Variables:
          BUCKET_NAME: !Ref PictureBucket
          QUEUE_URL: !Ref RecordQueue
      Events:
        DetectPictureApi:
          Type: HttpApi
          Properties:
            Path: /detect
            Method: get
            ApiId: !Ref ObjectDetectApi
            Auth:
              Authorizer: OpenIdAuthorizer
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref PictureBucket
        - SQSSendMessagePolicy:
            QueueName: !Ref RecordQueueName
        - RekognitionDetectOnlyPolicy: {}
  
  GetRecordsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/getRecords
      Handler: app.handler
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref RecordTable
      Environment:
        Variables:
          TABLE_NAME: !Ref RecordTable
      Events:
        GetRecordsApi:
          Type: HttpApi
          Properties:
            Path: /records
            Method: get
            ApiId: !Ref ObjectDetectApi
            Auth:
              Authorizer: OpenIdAuthorizer
  
  # Common Function
  SaveRecordFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/saveRecord
      Handler: app.handler
      Policies:
        - DynamoDBWritePolicy:
            TableName: !Ref RecordTable
      Environment:
        Variables:
          TABLE_NAME: !Ref RecordTable
      Events:
        RecordQueueEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt RecordQueue.Arn
            BatchSize: 10
  
  # SQS Queue
  RecordQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Ref RecordQueueName
      VisibilityTimeout: 60
  
  # S3 Bucket
  PictureBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref PictureBucketName
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - "*"
            AllowedMethods:
              - "GET"
              - "PUT"
            AllowedOrigins:
              - "*"
  
  WebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref WebsiteBucketName
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: "index.html"
  
  # S3 Bucket Policy
  PictureBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref PictureBucket
      PolicyDocument:
        Id: PictureBucketPolicy
        Version: 2012-10-17
        Statement:
          - Sid: PublicGetPicture
            Effect: Allow
            Principal: "*"
            Action: 's3:GetObject'
            Resource: !Sub "arn:aws:s3:::${PictureBucket}/*"

  WebsiteBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref WebsiteBucket
      PolicyDocument:
        Id: WebsiteBucketPolicy
        Version: 2012-10-17
        Statement:
          - Sid: PublicVisitWebsite
            Effect: Allow
            Principal: "*"
            Action: 's3:GetObject'
            Resource: !Sub "arn:aws:s3:::${WebsiteBucket}/*"

  # DynamoDB Table
  RecordTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref RecordTableName
      AttributeDefinitions:
        - AttributeName: "username"
          AttributeType: S
        - AttributeName: "key"
          AttributeType: S
      KeySchema:
        - AttributeName: "username"
          KeyType: HASH
        - AttributeName: "key"
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"
    
  # Cognito User Pool
  ObjectDetectUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      AdminCreateUserConfig:
        AllowAdminCreateUserOnly: False
      UserPoolName: !Ref ObjectDetectUserPoolName
      AutoVerifiedAttributes:
        - "email"
      Schema:
        - Mutable: False
          Name: "email"
          Required: True
      Policies:
        PasswordPolicy:
          MinimumLength: 6
          RequireLowercase: True
          RequireNumbers: False
          RequireSymbols: False
          RequireUppercase: True
  
  # Cognito App Client
  ObjectDetectUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref ObjectDetectUserPool
      GenerateSecret: False
      AllowedOAuthFlowsUserPoolClient: True
      AllowedOAuthFlows:
        - "implicit"
      CallbackURLs:
        - !Sub "https://${WebsiteBucket}.s3.amazonaws.com/index.html"
      LogoutURLs:
        - !Sub "https://${WebsiteBucket}.s3.amazonaws.com/index.html"
      SupportedIdentityProviders:
        - "COGNITO"
      AllowedOAuthScopes:
        - "email"
        - "openid"
      ExplicitAuthFlows:
        - "ALLOW_USER_PASSWORD_AUTH"
        - "ALLOW_REFRESH_TOKEN_AUTH"
        
  # Cognito Domain
  ObjectDetectUserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      Domain: !Ref ObjectDetectUserPoolClientDomain
      UserPoolId: !Ref ObjectDetectUserPool
    
Outputs:
  ApiEndpoint:
    Description: "Object Detect Api Endpoint URL"
    Value: !Sub "https://${ObjectDetectApi}.execute-api.${AWS::Region}.amazonaws.com"
  
  PictureURL:
    Description: "Picture Bucket URL"
    Value: !Sub "https://${PictureBucket}.s3.amazonaws.com"
  
  WebsiteURL:
    Description: "Object Detect App Website"
    Value: !Sub "https://${WebsiteBucket}.s3.amazonaws.com/index.html"
  
  RecordQueueUrl:
    Description: "Record Queue URL"
    Value: !Ref RecordQueue
    
  ObjectDetectUserPoolId:
    Description: "Object Detect App User Pool Id"
    Value: !Ref ObjectDetectUserPool
  
  ObjectDetectUserPoolDomain:
    Description: "Object Detect App User Pool Domain"
    Value: !Sub "https://${ObjectDetectUserPoolDomain}.auth.${AWS::Region}.amazoncognito.com"
  
  ObjectDetectUserPoolClientId:
    Description: "Object Detect App Client Id"
    Value: !Ref ObjectDetectUserPoolClient
  
  ObjectDetectUserPoolISSUrl:
    Description: "ISS URL"
    Value: !Sub "https://cognito-idp.${AWS::Region}.amazonaws.com/${ObjectDetectUserPool}"